language: node_js
node_js:
- '0.10'
after_script:
- "./node_modules/gulp/bin/gulp.js coveralls"
env:
  global:
    secure: GpjMUozJRh2rCSBg/viqp+/1r9rSN5NrFdBnSouSIhUh3ooGYNxReD+i0HAnUiLhljSNuxi5rEP6X4cfXv4mhJ7SmztFcgA+ay+kgr7tgeoeUarZhQAlywd/y3aQXypiK+JaSU3tLRYw09QxykkqVx/sb9XGMneCq3XD99S6MDU=
